name: Deploy Frontend to GCP

on:
  push:
    # paths:
    #   - 'frontend/**'
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: frontend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json') }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Configure Docker
      run: gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build and push Docker image
      env:
        NEXT_PUBLIC_API_URL: https://rezume-backend-195685071981.asia-south1.run.app
      run: |
        docker build \
          --build-arg NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
          -t asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resume-frontend/rezume-frontend:$GITHUB_SHA \
          .
        docker push asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resume-frontend/rezume-frontend:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy resume-frontend \
          --image asia-south1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/resume-frontend/frontend:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --port 3000
