name: Deploy Backend to GCP

on:
  push:
    # paths:
    #   - 'backend/**'
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Cache node_modules
      uses: actions/cache@v4
      with:
        path: backend/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    # - name: Configure Docker
    #   run: gcloud auth configure-docker
    
    - name: Docker login to Artifact Registry
      run: |
        gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://us-docker.pkg.dev
        
    - name: Build and push Docker image
      run: |
        docker build -t us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rezume-backend/rezume-backend:$GITHUB_SHA .
        docker push us-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/rezume-backend/rezume-backend:$GITHUB_SHA

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy rezume-backend \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/rezume-backend:$GITHUB_SHA \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated \
          --port 4000
